### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by wahmedswl** [betwixt-labs/bebop#124]
**Is your feature request related to a problem? Please describe.**
Hi, is this supported in browsers or is it simply for NodeJs.

Thanks

**Comment by AndrewMD5** [comment]
Bebop supports browsers and has no dependencies on node.

**Comment by wahmedswl** [comment]
Hi, its mean that it can be directly invoked from browser? Protobuf, its main hurdle is it don't support browser natively. So, is there any sample etc to use via browser eg: for RPC etc

Thanks

**Comment by AndrewMD5** [comment]
You should be able to add the package to your web project and used Bebop generated code without issue. The bebop compiler integrates into your developer environment to automate the code generation.

**Comment by wahmedswl** [comment]
How will RPC be done? bebop will generate http client code as well etc thats why asked for any eg etc to look into.

Thanks
