### ISSUE TITLE
Serializing a map?

### ISSUE THREAD

**Issue by FrankDMartinez** [betwixt-labs/bebop#226]
Hi.

I hope you are having a great new year so far.

If I wanted to serialize a map[string, string], what would be the recommended way to do that? Testing in the REPL at https://bebop.sh/repl suggests this can only be done if the map is embedded within a struct.

Thanks in advance.

**Comment by AndrewMD5** [comment]
Either:
```
message Test {
  1 -> map[string, string] myMap;
}
```

Or:
```
struct Test {
   map[string, string] myMap;
}
```

It isn’t possible to just serialize a type by itself, it must be inside a definition.

**Comment by FrankDMartinez** [comment]
Okay, thanks.
