### ISSUE TITLE
[NOTICE] Removal of the Dart generator in 3.0

### ISSUE THREAD

**Issue by andrewmd5** [betwixt-labs/bebop#252]
In an ongoing effort to consolidate resources and clean up the compiler, we will be removing the Dart generator from 3.0. It is the only generator which lacks support for unions, and with the introduction of services it now like two major features. 

We don't currently have a means to track usage for each generator, but we suspect it is the least popular. If there is community interest in keeping it, it will need to be voiced before 3.0.

**Comment by hot-moms** [comment]
Hi, Dart — rapidly growing language; 
starting with Dart 3, it introduced sealed classes, pattern matching and tuples (records in Dart terminology)

So, this means that the Dart generator has the potential to work with Union, there's no needs to remove Dart from supported languages, IMHO
