### ISSUE TITLE
bebopc.wasm

### ISSUE THREAD

**Issue by andrewmd5** [betwixt-labs/bebop#262]
I've found it pretty annoying that we can't host examples on sites such as Stackblitz. The only workaround to this is to compile the compiler to a WASI module.

Initial experiments are promising. Compiling to target WASM works without much trouble thanks to the [dotnet-wasi-sdk](https://github.com/SteveSandersonMS/dotnet-wasi-sdk). To get it fully working a few changes need to be made:
- Logging has to be majorly refactored as [Spectre.Console](https://spectreconsole.net/) makes calls to `System.Console` which raises `System.PlatformNotSupportedException` exceptions. 
- Disk access is tricky. WASI supports a virtual file system, so I'll need to play around with that; otherwise we'll need to have a WASM specific strategy for finding/parsing the config and spitting out generated code
- We don't rely heavily on reflection, however, I think this is still a great opportunity to refactor flag parsing.

I'll track progress here. I think this is worth having for 3.0 for the sake of making example apps easier to share.

**Comment by AndrewMD5** [comment]
Logging works now ([50db574](https://github.com/betwixt-labs/bebop/commit/50db574b908c37939463394d17c916cd2ad6ab1f)), thank you @patriksvensson for putting me on the right track. 

All that is left to do is the WASI wrapper for the .wasm build to orchestrate the runtime. Features such as `watch` won't work (for now, anyway.)

**Comment by andrewmd5** [comment]
implemented in #288
