### ISSUE TITLE
Bebop Usage of Trademarked Replit Logo

### ISSUE THREAD

**Issue by rayhanadev** [betwixt-labs/bebop#318]
Hello Bebop Team,

I am writing on behalf of Replit about your use of a Replit logo. I came across your site (hxxps[://]bebop[.]sh/) and saw that you are using one of our logos. This logo is a registered trademark of Replit (U.S. Trademark Reg. No. 7318975), and we do not consent to your use. We do not believe you have malicious intent, so we request that you change the icon so it does not use our logo.

Thank you for your prompt attention in this matter!

Kind regards,
Ray Arayilakath
Trust & Safety @ Replit

Screenshot of Usage of the Replit Logo on hxxps[://]bebop[.]sh/
<img width="394" alt="image" src="https://github.com/betwixt-labs/bebop/assets/72509475/2d34e831-b001-4626-b26b-46be411b3e19">

P.S. I would be willing to open a PR to change the icon to something more appropriate 👍

**Comment by andrewmd5** [comment]
Slow day? We'll be sure to get rid of the Replit based demos and switch to StackBlitz.

**Comment by rayhanadev** [comment]
Hello Andrew! Just to clarify, I noticed the Replit logo on your site and wanted to address it, as your demo is not hosted on Replit but is instead your own playground. I personally was confused when first clicking into it, hence why I wanted to raise it to your attention in a professional manner. Thanks for your understanding.

<img width="2560" alt="image" src="https://github.com/betwixt-labs/bebop/assets/72509475/5cb96021-b5e8-47d2-adc3-7740b811456d">
