### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by lucashan13** [betwixt-labs/bebop#319]
Hello!

I wish use bebop to real world service.

When defining a method for a service, how do I define a method that can be called without parameters?

**Comment by andrewmd5** [comment]
Currently, the workaround is to just define an empty structure, but I will update IDL and generation to support empty parameters

**Comment by lucashan13** [comment]
> Currently, the workaround is to just define an empty structure, but I will update IDL and generation to support empty parameters

Thank you your answer! I'll use like below:
```
struct Empty {}
```
