### ISSUE TITLE
Incorrect behavior of bebopc's --generator parameter on Windows

### ISSUE THREAD

**Issue by dimohy** [betwixt-labs/bebop#320]
**Describe the bug**
When using bebop in Visual Studio 2022, bebopc appears to fail due to a conflict between the token ':' in the --generator parameter and the ':' in the Windows driver as the OutputFile becomes an absolute path.

**To Reproduce**
1. In Visual Studio 2022 Create a console project
2. Install bebop, bebop-tools nugets
3. Create a BOP file and register CSPROJ file
```xml
  <ItemGroup>
    <Bebop Include="**/*.bop" OutputDir="./Models/" OutputFile="Models.g.cs" Namespace="BebopTest.Models" />
  </ItemGroup>
```
4. Add `BebopPrepareForBuildDiagnostic` CallTarget
```xml
  <Target Name="BebopPrepareForBuildDebug" AfterTargets="PrepareForBuild">
    <CallTarget Targets="BebopPrepareForBuildDiagnostic" />
  </Target>
```
5. Compile
6. Check for the following messages
```
1>Bebop Prepare For Build Diagnostic
1>Bebop Compiler Path = W:\dimohy\.nuget\packages\bebop-tools\3.0.4\tools\windows\x64\bebopc.exe
1>Bebop Output Directory = ./Models/
1>Bebop Output File = ./Models.g.cs
1>Bebop Target Language = cs
1>Bebop LangVersion = 9.0
1>Bebop Log Format = MSBuild
1>Bebop Namespace = BebopTest.Models
1>Input Schemas = "W:\Enjoy\BebopTest\models.bop"
1>Bebop Output = W:\Enjoy\BebopTest\Models\Models.g.cs
1>Incomplete generator token specified 'cs:W:\Enjoy\BebopTest\Models\Models.g.cs,namespace=BebopTest.Models,langVersion=9.0'.
1>
1>W:\dimohy\.nuget\packages\bebop-tools\3.0.4\build\bebop-tools.targets(66,9): error MSB3073: "..." 
```

**Expected behavior**
Compile successfully and the `Models.g.cs` file is created

**Bebop info:**
- Version: 3.0.4
- Runtime: .NET 9 Preview 2

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: 24H2

**Comment by andrewmd5** [comment]
Thank you for the detailed report. This is resolved in the latest release (3.0.5). If you still encounter the issue please comment here and I'll reopen.
