### ISSUE TITLE
Rust lab benchmarks do not use provided profile

### ISSUE THREAD

**Issue by owobred** [betwixt-labs/bebop#327]
**Describe the bug**
When running the rust benchmarks in `/Laboratory/Rust/benchmarking`, the `bench` profile is ignored. This means that neither the LTO nor the `codegen-units` used when building.

**To Reproduce**
1. Go to `/Laboratory/Rust/benchmarking`
2. Run `cargo bench`
3. See warning at top of output

**Expected behavior**

**Screenshots / Snippets**
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/bred/scratch/bebop/Laboratory/Rust/benchmarking/Cargo.toml
workspace: /home/bred/scratch/bebop/Laboratory/Rust/Cargo.toml
```
**Info**
Tested on https://github.com/betwixt-labs/bebop/commit/03502a9fe5d0aca847704c5bf97a4b312868d568 using Ubuntu 23.10 on wsl2.
dotnet 8.0.103, rustc 1.79.0-nightly (aa1c45908 2024-04-06)

**Additional context**
This should probably be fixed by moving the `[profile.bench]` section from `/Laboratory/Rust/benchmarking/Cargo.toml` to `/Laboratory/Rust/Cargo.toml`.
This has no real effect on benchmarks, other than making bincode marginally faster when serializing.

**Comment by andrewmd5** [comment]
Thanks for reporting this. Would you mind submitting a PR with the necessary changes?
