### ISSUE TITLE
[DOCS] There is no "real" documentation for how to use Bebop on JS/TS

### ISSUE THREAD

**Issue by castarco** [betwixt-labs/bebop#329]
**Is your feature request related to a problem? Please describe.**

The current documentation for JS/TS/NodeJS only tells us how to install a couple of packages and compile Bebop definitions... but not how to integrate the generated code.

I guess there is a strong assumption that Bebop will be used only via Tempo, but there are other potential use cases, such as serializing/unserializing messages that go through "queues" such as Kafka.

**Describe the solution you'd like**

It would be nice having either a specification for the exposed objects & interfaces, or a short guide telling:
- How to serialize a JS/TS object with Bebop
- How to unserialize a Bebop bytes stream into a JS/TS object.

**Describe alternatives you've considered**

None, I really believe that the documentation is missing crucial information.

I also think that this might be one of the main reasons why Bebop usage is so low in the NodeJS ecosystem (the value proposition seems quite appealing, but very few people rely on it for JS/TS projects).

**Comment by andrewmd5** [comment]
Thank you for opening this issue. Bebop is definitely meant to be used standalone, Tempo is mostly sugar. 

In TS land it should be as simple as importing the generated class, then:

```ts
const data = new Person({
    name: "Spike Spiegel",
    age: 27
}).encode();


const person = Person.decode(data);
```

If you don't mind contributing, you can flesh out the documentation [here](https://github.com/betwixt-labs/bebop/blob/master/docs/src/content/docs/guide/getting-started-typescript.mdx).

I'm currently in the hospital so I'm unable to do much work for the time being.

**Comment by castarco** [comment]
Thank you @andrewmd5 , take care. I'll have a look into the documentation source code to see if I can push a PR.

Cheers.

**Comment by andrewmd5** [comment]
@castarco first pass at this

https://github.com/betwixt-labs/bebop/pull/334/commits/894e720927513c751c35a65aa4c7af2a2ea14230

**Comment by andrewmd5** [comment]
This is implemented now https://docs.bebop.sh/guide/getting-started-typescript/
