### ISSUE TITLE
bebop-tools in C# does not auto generate on build

### ISSUE THREAD

**Issue by MoodieG** [betwixt-labs/bebop#332]
**Describe the bug**
I followed the documentation in [getting started with C#](https://docs.bebop.sh/guide/getting-started-csharp/) but was not able to auto generate a C# file with bebop tools

**To Reproduce**

I am using Visual Studio version 17.10

1. Create a new .NET 8.0 console application.
2. Add bebop and bebop tools as package dependencies
3. Add the following item group to your csproj file:
```
<ItemGroup>
  <Bebop Include="**/*.bop" OutputDir="./Models/" OutputFile="IpcModels.g.cs" Namespace="RainwayIPC.Models" />
</ItemGroup>
```
4. Add any `.bop` file to the project. I added `test.bop` file with the following contents:
```
struct Hello {
   int32 x;
   int32 y;
}
```
5. Build the project. 
6. `IpcModels.g.cs` is nowhere to be found and cannot reference the `Hello` struct.

**Expected behavior**
The `IpcModels.g.cs` file should get generated.

**Screenshots / Snippets**
NA

**Bebop info:**
- Version: 3.0.9
- Runtime: .NET

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 10.0.22631

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by andrewmd5** [comment]
Thanks for the report. Two things:

Add this to your csproj to see what it print out:
```
<Target Name="BebopPrepareForBuildDebug" AfterTargets="PrepareForBuild">
  <CallTarget Targets="BebopPrepareForBuildDiagnostic"/>
</Target> 
```

Make sure Visual Studio didn't automatically generate a "remove" include for the .bop file you added (check the csproj)

**Comment by MoodieG** [comment]
Adding that to my csproj file generates the expected file. However, only in debug configuration. 

In release configuration I get the following error but I believe it is not expected to work in Release. 

`1>bebopc : error BOP1000: IO_SharingViolation_File,`

Any idea why the file is not auto generating without calling `BebopPrepareForBuildDiagnostic` target?

**Comment by MoodieG** [comment]
Just bumping this thread.

**Comment by andrewmd5** [comment]
Still working on a fix.
