### ISSUE TITLE
Non-conventional C# multi-dimensional arrays generated

### ISSUE THREAD

**Issue by Anatoly03** [betwixt-labs/bebop#346]
**Describe the bug**

In [C#, a multi-dimensional array](https://www.w3schools.com/cs/cs_arrays_multi.php) is declared with commas in-between the square brackets (`[,]`), and not conventionally with square brackets stacked (`[][]`).

https://github.com/betwixt-labs/bebop/blob/2108a61d874c6dd10eb983d677b897bc263327a8/Core/Generators/CSharp/CSharpGenerator.cs#L1341-L1342

This line should not append the type recursively to be `(recursive call)[]`, but instead read out the dimension of the array, and write commas by formula by pseudo-code`"[" + ",".repeat(dimension - 1) + "]"`.

**To Reproduce**

```bebop
struct FooBar {
    uint8[][] foo;
    string[][][] bar;
}
```

**Expected behavior**

The generated C# code should have multi-dimensional arrays with the respective commas `[,]` and `[,,]`

**Screenshots / Snippets**

```cs
// struct WorldInit {
//     uint16 width;
//     uint16 height;
//     BlockData[][] background;
//     BlockData[][] foreground;
// }
public partial class WorldInit : global::Bebop.Runtime.BaseBebopRecord, global::Bebop.Runtime.IDecodable<WorldInit>, global::System.IEquatable<WorldInit> {
    ...
    public global::PixelWalker.MessageLibrary.BlockData[][] Background { get; init; }
    [global::System.Diagnostics.CodeAnalysis.NotNull, global::System.Diagnostics.CodeAnalysis.DisallowNull]
    public global::PixelWalker.MessageLibrary.BlockData[][] Foreground { get; init; }
    ...
}
```

**Bebop info:**
- Version: 3.0.14
- Runtime: .NET

```html
    <ItemGroup>
      <PackageReference Include="bebop" Version="3.0.14" />
      <PackageReference Include="bebop-tools" Version="3.0.14">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <Bebop Include="**/*.bop" OutputDir="./Models/" OutputFile="Models.g.cs" Namespace="PixelWalker.MessageLibrary" />
    </ItemGroup>
```

**Desktop (please complete the following information):**
 - OS: macOS-Intel
 - Version Ventura

**Comment by andrewmd5** [comment]
Thanks for opening this issue. Bebop only supports jagged arrays and has no concept for multi-dimensional arrays.

While C# _does_ support multi-dimensional arrays, languages Bebop also supports such as Rust and Dart do not. So we only generate data structures that every language can support.

**Comment by Anatoly03** [comment]
Thanks for replying. If I understand right, the bebop generators are language specific, so this can be customized? A simple recursive function that stops on a non array can yield the array dimensions. Could this be implemented in the lines mentioned above?

https://github.com/betwixt-labs/bebop/blob/2108a61d874c6dd10eb983d677b897bc263327a8/Core/Generators/CSharp/CSharpGenerator.cs#L1312-L1348

Here's an example of how this function could look like:

```cs
private int ArrayDimension(in TypeBase type)
{
    return type switch
    {
        ArrayType at => 1 + ArrayDimension(at.MemberType),
        _ => 0
    };
}
```

**Comment by Emalton** [comment]
@andrewmd5 We really could use this. Crippling bebop wouldn't be ideal, as both languages that we're using support multi-dimensional arrays. Perhaps a warning that this is only supported on some languages in the readme or something would be best.

**Comment by SirusDoma** [comment]
> @andrewmd5 We really could use this. Crippling bebop wouldn't be ideal, as both languages that we're using support multi-dimensional arrays. Perhaps a warning that this is only supported on some languages in the readme or something would be best.

I don't think supporting specific features that only supported specific language is a good idea. What happen if we want to support such thing in other languages too? everything become a mess when we do that.

I do agree with notion of making sure every features are equally supported in all languages that bebop support. Perhaps this should be extendable via chordc/plugin system instead.

**Comment by andrewmd5** [comment]
> > @andrewmd5 We really could use this. Crippling bebop wouldn't be ideal, as both languages that we're using support multi-dimensional arrays. Perhaps a warning that this is only supported on some languages in the readme or something would be best.
> 
> I don't think supporting specific features that only supported specific language is a good idea. What happen if we want to support such thing in other languages too? everything become a mess when we do that.
> 
> I do agree with notion of making sure every features need to be equally supported in all languages that bebop support. Perhaps this should be extendable via chordc/plugin system instead or invent opinionated implementation like `union` that could cover all languages (because `union` is originally not a thing in C#) but I would rather prefer the chordc/plugin option.

Using chords would be the best course of action. Currently only generators are supported via the extension system, so you’d have to create a new C# generator which is a bit annoying, so I need to spend some time on finishing the contribution extensions so you can extend existing generators. I’ll put it on my TODO for the week.

**Comment by Anatoly03** [comment]
> I don't think supporting specific features that only supported specific language is a good idea. What happen if we want to support such thing in other languages too? everything become a mess when we do that.

 @SirusDoma No, this wouldn't affect the result in other languages. The change would only be in the C# generator, not affecting other languages, and not affecting Bebop files.
 
 In particular, several lines of code that print out the array in C# would change.

**Comment by Anatoly03** [comment]
I will close this issue. There's a piece of code being generated with jagged arrays that doesn't have a simple analogue in multi-dimensional arrays, particularly the initialization `new bool[field0][]` cannot be inferred as `new bool[field0, ]`.

**Comment by SirusDoma** [comment]
> > I don't think supporting specific features that only supported specific language is a good idea. What happen if we want to support such thing in other languages too? everything become a mess when we do that.
> 
> @SirusDoma No, this wouldn't affect the result in other languages. The change would only be in the C# generator, not affecting other languages, and not affecting Bebop files.
> 
> In particular, several lines of code that print out the array in C# would change.

And yet you can always say the same for the other language, say, if Go support some sort of type that C# doesn't have: by your logic its fine to add it into bebop, and then bebop has to maintain these 2 exclusive things between these languages and things will become messy once other language have similar justification.

If it doesn't have to do or affect the other language as you claim, do it in plugin system so it stays there exclusively, don't pollute the main repo which has to support multiple languages.
