### ISSUE TITLE
schema support namespace feature for big project

### ISSUE THREAD

**Issue by killop** [betwixt-labs/bebop#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AndrewMD5** [comment]
You can already specify a namespace for generated code by doing:
`./bebopc --cs [output_file] --namespace see.you.in.space.cowboy`

Then all compiled schemas will be placed under this namespace. Is that what you were looking for?

**Comment by killop** [comment]
Thank you for your quick answer.
